import type { Staff, Location, AttendanceRecord, DressItem, SalaryRecord } from "./types";

const today = new Date().toISOString().split("T")[0]!;
const thisMonth = today.substring(0, 7);

export const seedLocations: Location[] = [
  {
    id: "loc1",
    name: "Central Bank HQ",
    address: "MG Road, Connaught Place",
    city: "New Delhi",
    latitude: 28.6315,
    longitude: 77.2167,
    radius: 200,
    contactPerson: "Ramesh Kumar",
    contactPhone: "9876543210",
    active: true,
  },
  {
    id: "loc2",
    name: "Tech Park Gate A",
    address: "Sector 62, Electronic City",
    city: "Bengaluru",
    latitude: 12.9716,
    longitude: 77.5946,
    radius: 150,
    contactPerson: "Priya Sharma",
    contactPhone: "9988776655",
    active: true,
  },
  {
    id: "loc3",
    name: "Metro Station North",
    address: "Rajiv Chowk Metro",
    city: "New Delhi",
    latitude: 28.6328,
    longitude: 77.2197,
    radius: 100,
    contactPerson: "Suresh Nair",
    contactPhone: "9911223344",
    active: true,
  },
  {
    id: "loc4",
    name: "Hospital Complex",
    address: "AIIMS Main Campus",
    city: "New Delhi",
    latitude: 28.5672,
    longitude: 77.2099,
    radius: 300,
    contactPerson: "Dr. Admin Office",
    contactPhone: "9800011122",
    active: true,
  },
];

export const seedStaff: Staff[] = [
  {
    id: "s1",
    name: "Rajesh Singh",
    employeeId: "SEC-001",
    designation: "Senior Guard",
    phone: "9876501001",
    locationId: "loc1",
    joinDate: "2022-03-15",
    status: "active",
    salary: 18000,
    dressSize: "L",
    dressIssued: true,
    dressIssuedDate: "2024-01-10",
  },
  {
    id: "s2",
    name: "Mukesh Pandey",
    employeeId: "SEC-002",
    designation: "Guard",
    phone: "9876501002",
    locationId: "loc1",
    joinDate: "2023-06-01",
    status: "active",
    salary: 15000,
    dressSize: "M",
    dressIssued: true,
    dressIssuedDate: "2024-01-10",
  },
  {
    id: "s3",
    name: "Sunil Yadav",
    employeeId: "SEC-003",
    designation: "Supervisor",
    phone: "9876501003",
    locationId: "loc2",
    joinDate: "2021-11-20",
    status: "active",
    salary: 22000,
    dressSize: "XL",
    dressIssued: true,
    dressIssuedDate: "2023-12-05",
  },
  {
    id: "s4",
    name: "Anil Kumar",
    employeeId: "SEC-004",
    designation: "Guard",
    phone: "9876501004",
    locationId: "loc2",
    joinDate: "2023-09-10",
    status: "active",
    salary: 15000,
    dressSize: "L",
    dressIssued: false,
  },
  {
    id: "s5",
    name: "Vinod Sharma",
    employeeId: "SEC-005",
    designation: "Guard",
    phone: "9876501005",
    locationId: "loc3",
    joinDate: "2024-01-05",
    status: "active",
    salary: 15000,
    dressSize: "M",
    dressIssued: true,
    dressIssuedDate: "2024-02-01",
  },
  {
    id: "s6",
    name: "Deepak Mishra",
    employeeId: "SEC-006",
    designation: "Senior Guard",
    phone: "9876501006",
    locationId: "loc3",
    joinDate: "2022-07-18",
    status: "on-leave",
    salary: 18000,
    dressSize: "L",
    dressIssued: true,
    dressIssuedDate: "2023-08-15",
  },
  {
    id: "s7",
    name: "Ramesh Tiwari",
    employeeId: "SEC-007",
    designation: "Guard",
    phone: "9876501007",
    locationId: "loc4",
    joinDate: "2023-03-22",
    status: "active",
    salary: 15000,
    dressSize: "XL",
    dressIssued: true,
    dressIssuedDate: "2024-01-15",
  },
  {
    id: "s8",
    name: "Santosh Gupta",
    employeeId: "SEC-008",
    designation: "Supervisor",
    phone: "9876501008",
    locationId: "loc4",
    joinDate: "2020-05-10",
    status: "active",
    salary: 22000,
    dressSize: "M",
    dressIssued: true,
    dressIssuedDate: "2023-06-20",
  },
];

export const seedAttendance: AttendanceRecord[] = [
  {
    id: "a1",
    staffId: "s1",
    staffName: "Rajesh Singh",
    locationId: "loc1",
    locationName: "Central Bank HQ",
    date: today,
    checkIn: new Date().toISOString(),
    checkInLat: 28.6315,
    checkInLng: 77.2167,
    status: "present",
    verifiedByLocation: true,
  },
  {
    id: "a2",
    staffId: "s2",
    staffName: "Mukesh Pandey",
    locationId: "loc1",
    locationName: "Central Bank HQ",
    date: today,
    checkIn: new Date(Date.now() - 1800000).toISOString(),
    checkInLat: 28.6315,
    checkInLng: 77.2167,
    status: "late",
    verifiedByLocation: true,
  },
  {
    id: "a3",
    staffId: "s3",
    staffName: "Sunil Yadav",
    locationId: "loc2",
    locationName: "Tech Park Gate A",
    date: today,
    checkIn: new Date(Date.now() - 7200000).toISOString(),
    checkInLat: 12.9716,
    checkInLng: 77.5946,
    status: "present",
    verifiedByLocation: true,
  },
  {
    id: "a4",
    staffId: "s6",
    staffName: "Deepak Mishra",
    locationId: "loc3",
    locationName: "Metro Station North",
    date: today,
    status: "absent",
    verifiedByLocation: false,
  },
];

export const seedDress: DressItem[] = [
  { id: "d1", staffId: "s1", staffName: "Rajesh Singh", itemType: "Shirt", size: "L", issuedDate: "2024-01-10", condition: "Good" },
  { id: "d2", staffId: "s1", staffName: "Rajesh Singh", itemType: "Trousers", size: "L", issuedDate: "2024-01-10", condition: "Good" },
  { id: "d3", staffId: "s1", staffName: "Rajesh Singh", itemType: "Boots", size: "9", issuedDate: "2024-01-10", condition: "Worn", nextReplacement: "2025-01-10" },
  { id: "d4", staffId: "s2", staffName: "Mukesh Pandey", itemType: "Shirt", size: "M", issuedDate: "2024-01-10", condition: "New" },
  { id: "d5", staffId: "s3", staffName: "Sunil Yadav", itemType: "Jacket", size: "XL", issuedDate: "2023-12-05", condition: "Good" },
  { id: "d6", staffId: "s3", staffName: "Sunil Yadav", itemType: "Cap", size: "XL", issuedDate: "2023-12-05", condition: "Worn" },
];

export const seedSalary: SalaryRecord[] = [
  { id: "sal1", staffId: "s1", staffName: "Rajesh Singh", month: thisMonth, basicSalary: 15000, allowances: 3000, deductions: 0, netSalary: 18000, status: "pending" },
  { id: "sal2", staffId: "s2", staffName: "Mukesh Pandey", month: thisMonth, basicSalary: 13000, allowances: 2000, deductions: 0, netSalary: 15000, status: "pending" },
  { id: "sal3", staffId: "s3", staffName: "Sunil Yadav", month: thisMonth, basicSalary: 19000, allowances: 3000, deductions: 0, netSalary: 22000, status: "paid", paidDate: new Date().toISOString() },
  { id: "sal4", staffId: "s4", staffName: "Anil Kumar", month: thisMonth, basicSalary: 13000, allowances: 2000, deductions: 0, netSalary: 15000, status: "pending" },
  { id: "sal5", staffId: "s5", staffName: "Vinod Sharma", month: thisMonth, basicSalary: 13000, allowances: 2000, deductions: 0, netSalary: 15000, status: "pending" },
  { id: "sal6", staffId: "s7", staffName: "Ramesh Tiwari", month: thisMonth, basicSalary: 13000, allowances: 2000, deductions: 0, netSalary: 15000, status: "paid", paidDate: new Date().toISOString() },
  { id: "sal7", staffId: "s8", staffName: "Santosh Gupta", month: thisMonth, basicSalary: 19000, allowances: 3000, deductions: 0, netSalary: 22000, status: "paid", paidDate: new Date().toISOString() },
];
